### ISSUE TITLE
set tab index to -1 onDeactivate

### ISSUE THREAD

**Issue by jessemc98** [davidtheclark/focus-trap#21]
Is there a built in way to have all focusable elements receive a tabIndex of -1 onDeactivate?
This would be useful when you have, for example, a navbar which is not unmounted from the dom when hidden, i.e. translated off screen. If we don't set tabIndex to -1 when it is hidden, focus ends up hidden offscreen.

One suggestion for how we can go about adding this feature is by adding a function which runs before the trap is deactivated which sets the tabIndex if options.autoDisableFocus is true, this is how I am currently doing it in my code but it defeats the purpose of using this 'library' in the first place.

Sorry if there is already an inbuilt way to do this, if there is I could not find it. Im glad to help integrate the feature if you would like to add it.

**Comment by davidtheclark** [comment]
Interesting point, @jessemc98. However, I don't think that the issue is within the domain of this library. A focus-trap does not enable and disable *the ability to focus elements*: instead, it traps focus within a set of focusable elements. If you want to make a previously focusable element *un*focusable, you can do so with some other JS — but that seems unrelated to the focus-trapping problem this library is meant to solve.

**Comment by jessemc98** [comment]
Thanks for the hasty reply,

I guess you're right, I just thought it might be a useful feature since it is a pretty common use case in most sites with a mobile navigation and it would take away the need to query the dom for the focusables twice.

 I see your point, separation of concerns is important but the only time where I can see the feature I described being useful is when using a focus trap.
