### ISSUE TITLE
Position lost after focus on tabindex="-1"

### ISSUE THREAD

**Issue by MrEscaGreenwing** [davidtheclark/focus-trap#36]
Hi @davidtheclark,
I'm currently using your `focus-trap` and it's working totally fine. Unfortunately I ran into a problem just now:
My use case is a modal with a user help which consists of a table of contents, some headings and blocks of information. A click in the table of contents leads to a focus on the corresponding heading with the help of `tabindex="-1"`. So far, so good. Now I want to tab to next tabbable element - in this case the first following block of information - but that doesn't work like I'd planned. The reason is that elements with `tabindex="-1"` are not part of the `tabbableNodes`-Array and therefore can't be found in the context of the modal. The consquence is that the focus is set back to the first element of the array instead of jumping to the next expected one. The user loses his position in the modal and gets irritated.
Furthermore is the use of `tabindex="0"` no option because the headings shouldn't be tabbable in general. The tabindex is just for the focus (because of accessibilty reasons).

Now I want to know if this sounds like a valid use case your focus-trap could handle? Unfortunately that would mean to make changes in your `tabbable`-module and in this one. Elements with `tabindex="-1"` have to be part of the `tabbableNodes` (maybe using a function parameter like `registerNegativeIndeces=true`?) and afterwards the `handleTab`-function needs to ignore all those elements. Would that be possible?

**Comment by davidtheclark** [comment]
Hi @MrEscaGreenwing. Thanks for explaining the situation. I don't think we want to add elements with `tabindex="-1"` to `tabbable`, because those are not *actually* tabbable. Maybe we could reframe your problem ... here's what it sounds like to me:

If I have set focus on the non-tabbable Element X within a focus trap, then the user presses tab, I expect focus to move to *the next tabbable element after Element X*. But what I'm seeing is that it moves to the first tabbable element in the trap.

Is that an accurate summary? If so, I agree that it would be a good thing to fix.

**Comment by MrEscaGreenwing** [comment]
Yeah, that's exactly the problem :) If you can imagine a solution without touching `tabbable` that would be even better. Because I can totally see your point in not adding elements with `tabindex="-1"` to the array.

**Comment by davidtheclark** [comment]
I think it might take some significant refactoring — but this package isn't that big anyway. Here's the way I'd imagine this might work: Instead of focus-trap tracking the `currentFocusIndex`, hijacking the `tab` key, and manually moving focus based on whether you hit `tab` or `shift+tab`, it would do this *only hijacking attempts to focus outside the focus-trap.* So while you tab through the track, focus-trap does nothing. But somehow it detects if you've tabbed *out of* the trap, and if so it hijacks your focus, putting it on the first or last tabbable element (Based on whether you hit `tab` or `shift+tab`).

Does that make sense? @MrEscaGreenwing are you interested in working on a PR for this?

**Comment by MrEscaGreenwing** [comment]
@davidtheclark sounds like a plan to me. I would at least try to refactor it for you. But I guess it will take some time because of some other workload and coming vacation :) If that's no problem for you, I'm fine with it!

**Comment by davidtheclark** [comment]
@MrEscaGreenwing I'd love the collaboration — happy to wait until you're ready.

**Comment by MrEscaGreenwing** [comment]
@davidtheclark I'm back and rethought your solution. But there is one little thing I want to discuss with you before I start. The use case would be the tab from the last tabbable element of the container back to the first one. Therefore I apparently need to leave the trap deliberately before I can check if the new focused element is not part of it. Afterwards I have to set it back to the first element within the container. That means we would set the focus two times with this operation while leaving the trap for a short moment. Feels a little bit odd, doesn't it? But if you don't have any concerns about this I'll go on.

**Comment by davidtheclark** [comment]
> That means we would set the focus two times with this operation while leaving the trap for a short moment. Feels a little bit odd, doesn't it?

The only problem I think would if there's a noticeable flash of the focus outline — it moves outside the trap, then quickly jumps back to the top of the trap. We already essentially do this with https://github.com/davidtheclark/focus-trap/blob/master/index.js#L181, and I think it's working ok. But if not, you could try experiment with other techniques. For example, what if you listen for `blur` events on the first and last focusable elements in the trap, and check their `relatedTarget`.

Summary: I don't have any concerns unless it feels weird. And the only way to know that is to try it out 🤷‍♂️

**Comment by davidtheclark** [comment]
Closed by #38.
