### ISSUE TITLE
Focus trap cant find focusable element if only one focusable element

### ISSUE THREAD

**Issue by oskarkvamme** [davidtheclark/focus-trap#44]
Example:
```html
<div class="modal">
  <button>Click Me</button>
</div>
```
![image 1](https://user-images.githubusercontent.com/697608/35442778-bbf08106-02a8-11e8-878c-9bc9c7f87032.png)

**Comment by davidtheclark** [comment]
@oskarkvamme I don't think this is a bug in the library, because I can't reproduce in a simple demo. Can you reproduce it outside of your particular app, outside React, etc.? I suspect you may be creating the focus trap at the wrong time in a component's lifecycle or something, so the elements don't exist yet?

**Comment by davidtheclark** [comment]
Closing as stale.
