### ISSUE TITLE
[2.4.4] dist/focustrap.js doesn't exist

### ISSUE THREAD

**Issue by jeroencornelissen** [davidtheclark/focus-trap#50]
In the `package.json` the `main` points to `dist/focustrap.js` but that file doesn't exist. This should be `dist/focus-trap.js` or `index.js` like it used to be.

**Comment by davidtheclark** [comment]
Thanks, @jeroencornelissen. Should be fixed in 2.4.5.

**Comment by vladimyr** [comment]
@davidtheclark Actually, now it is fully broken :cry: 

If someone tries to use it from unpkg.com they'll get error due to `require` not being implemented: 
https://jsbin.com/remegiyeva/edit?html,console
However if you point to `dist/focus-trap.js`; which should be where `main` points to; you get this:
https://jsbin.com/nagicadifu/edit?html,console

Bottom line, `main` should always point to the umd bundle :wink:

**Comment by davidtheclark** [comment]
@vladimyr Are you sure you're looking in the right place, according to https://github.com/davidtheclark/focus-trap#installation? 

https://unpkg.com/focus-trap@2.4.5/dist/focus-trap.js and https://unpkg.com/focus-trap@2.4.5/dist/focus-trap.min.js exist and seem to work fine.

In 2.4.5 `main` actually points to `index.js`, not to `dist/focus-trap.js`.

> Bottom line, main should always point to the umd bundle 😉

I don't agree, because that adds unnecessary stuff for module users.

**Comment by vladimyr** [comment]
> @vladimyr Are you sure you're looking in the right place, according to https://github.com/davidtheclark/focus-trap#installation?

Yeah, you are right, I missed that one :man_facepalming: Although it should be probably more helpful if documentation gives you something like this:
```html
<!-- development -->
<script source="https://unpkg.com/focus-trap@2.4.5/dist/focus-trap.js"></script>

<!-- production -->
<script source="https://unpkg.com/focus-trap@2.4.5/dist/focus-trap.min.js"></script>
```
because [Vue does that](https://vuejs.org/v2/guide/installation.html#CDN) and React used to show that `<script>` snippet on their homepage too... It is easier if you can just c/p it :slightly_smiling_face: 

> I don't agree, because that adds unnecessary stuff for module users.

Well, technically speaking it does add umd wrapper _bloat_ and I'm perfectly aware that at the end of the day it is your call to decide. However, just in case you missed it, all packages listed on [unpkg.com homepage](https://unpkg.com/) except `react` & `react-dom` (Vue is not listed there but points to umd bundle too) do the opposite so you are kinda going against the flow...
