### ISSUE TITLE
Use native Object.assign instead of xtend

### ISSUE THREAD

**Issue by jimmywarting** [davidtheclark/focus-trap#66]
[xtend](https://github.com/Raynos/xtend) can easily be replaced with [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

This reduce the dependencies and possible also avoid duplicated versions where some package don't use the same version range for the xtend package

```js
// immutable
Object.assign({}, a, b)

// mutable
Object.assign(a, b)
```

**Comment by davidtheclark** [comment]
We're using xtend because IE does not support `Object.assign`. xtend is extremely small and extremely stable, so I'm not really worried about it as a dependency. I figure it's better to inline that tiny function than to expect the user to polyfill `Object.assign` when they might not have done that otherwise.
