### ISSUE TITLE
Clicking focus trap "activate" button and using clickOutsideDeactivates has a weird behavior with mousedown.

### ISSUE THREAD

**Issue by DennisMartinez** [davidtheclark/focus-trap#89]
Hello,

I'm having a problem that I'm unsure is caused by focus trap or possibly my implementation. The problem I'm running in to is I have a button, when you click on this button it opens a menu. I use `clickOutsideDeactivates` to close the menu when the user clicks outside. If the user clicks on the button to open the menu while the menu is open, it'll close and reopen the menu. I'm guessing this is because the deactivate code is on `mousedown` and not `mouseup`. I made a codesandbox to demonstrate my problem. https://codesandbox.io/s/blissful-morse-74vkb

I got around the issue (sort of) by checking if the target element is the `state.nodeFocusedBeforeActivation` and I can make a pr with a cleaner version of this than what's in the codesandbox if it's useful. Maybe there is already a solution for this?

**Comment by jtomaszewski** [comment]
See https://github.com/davidtheclark/focus-trap/pull/88 . Would that solve your solution? I even added a demo there with very similar example to the one you're describing here, If I understand it correctly.

Please give me some feedback because I was thinking about merging https://github.com/davidtheclark/focus-trap/pull/88 any moment, I just want to be sure that it is useful for other ppl as well ;)

**Comment by DennisMartinez** [comment]
@jtomaszewski,

This is exactly what I need. I like this approach. I'll close this in favor of https://github.com/davidtheclark/focus-trap/pull/88. Thank you!

**Comment by jtomaszewski** [comment]
Thanks. FYI, https://github.com/davidtheclark/focus-trap/pull/88 has been merged now , maybe soon it will be released to npm as well.
